export const CHATS = {
  FETCH_CHATS: "FETCH_CHATS",
  CURRENT_CHAT: "CURRENT_CHAT",
};
export const MESSAGES = {
  FETCH_MESSAGES: "FETCH_MESSAGES",
  READ_MESSAGES: "READ_MESSAGES",
};

export const USERS = {
  FETCH_USERS: "FETCH_USERS",
};

export const USER = {
  FETCH_PROFILE: "FETCH_PROFILE",
};
