import type { Metadata } from "next";
import LayoutClient from "./LayoutClient";
import "./globals.css";

export const metadata: Metadata = {
  title: "Chat-A-Tive",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
